name: Build

on:
  pull_request:
  push:
    tags: [v*]

jobs:
  build:
    strategy:
      matrix:
        core_tag:
          - 3261.v9c670a_4748a_9-8-jdk11-2bbea7f
          - 3261.v9c670a_4748a_9-8-jdk17-2bbea7f
          - 3261.v9c670a_4748a_9-8-jdk21-2bbea7f
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: Dwolla/jenkins-agents-workflow/.github/actions/build@main
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BASE_TAG: ${{ matrix.core_tag }}
          TAG_NAME: CORE_TAG
          IMAGE_NAME: dwolla/jenkins-agent-sbt
  build-complete:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The build completed successfully"